services:
  - type: web
    name: scrape-namegrep-api
    env: node
    nodeVersion: 20
    buildCommand: npm install
    startCommand: node api/index.js
    envVars:
      - key: NODE_ENV
        value: production
